Repository ynput/ayon-substance-painter, pull requests merged in 2025-04, with the labels that each got.

#36 Support for $uvTileName token in texture name
  client/ayon_substancepainter/api/lib.py
  client/ayon_substancepainter/plugins/publish/collect_textureset_images.py
  server/settings/creator_plugins.py
Labels: type: enhancement, sponsored

#39 fix the ayon server import
  server/settings/creator_plugins.py
Labels: type: bug

#40 Settings: Fix layout -> _layout attribute for Settings model
  server/settings/creator_plugins.py
Labels: type: bug, community
